# .travis.yml
language: java

jdk:
  - oraclejdk8

install:
  - curl -s toast.sh/install-v3 | bash

before_script:
  - ~/toaster/toast.sh c REGION ap-northeast-2
  - ~/toaster/toast.sh c BUCKET repo.nalbam.com

script:
  - ~/toaster/toast.sh v $TRAVIS_BRANCH
  - mvn clean package

after_success:
  - mvn cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report

deploy:
  provider: s3
  region: ap-northeast-2
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  skip_cleanup: true
  acl: public_read
  local_dir: target
  upload_dir: maven2/com/nalbam/nalbam-config-client

notifications:
  slack: nalbam:lZm5eyurcsoKxZgHSnNZGQYY
