# .travis.yml
language: java

jdk:
  - oraclejdk8

install:
  - curl -s toast.sh/install | bash

before_script:
  - ~/toaster/toast.sh version next $TRAVIS_BRANCH $TOAST_TOKEN nalbam

script:
  - mvn clean package

after_success:
  - mvn cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
  - ~/toaster/toast.sh version save none $TOAST_TOKEN nalbam

deploy:
  provider: s3
  region: ap-northeast-2
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  skip_cleanup: true
  acl: public_read
  local_dir: target
  upload-dir: maven2/com/nalbam/nalbam-config-client

notifications:
  slack: nalbam:lZm5eyurcsoKxZgHSnNZGQYY
